env:
  matrix:
    - PYTHON_VERSION="3.6.8"
    - PYTHON_VERSION="3.7.3"
  global:
    - secure: yymikcfFTbyLj/+K9a8gjC/3e3sARM8fVCGRR8yW/9sJVshIqxWKjA1eKMjecmgfrF01fYocRDQDNSB0fBWYFUx2KQnsrxHWjF2MXyCZ1WfF065InFniigPvuMAz7dxZCQzJmn9Ggv09X4/+3O/biAqQduj+M9eYk7oV01fFACmI/IYJou9myN8Lv+CwkhUL+Yd6G7zUP9Aa/RpUyQ+HdYCsP2n0IUWvOTdnwqspMpuEQthdbZZ8wOVqY/KStcLVu33kaT7+4Z3SJsGFkBR9PXh+cP1lECOvdAFOA9ZFRV/pbdnIrG2HLL7pS0s57e+eQ62qVxw2arYMz/8IRLM9IUZOsRXK0MyFSe8T1mNqMQzwvORTfpTD6FNpfDOiYiGdL06GJ3h5YYCNrABbEC5DVR/zxqAyiun7tDnlNd8pvJ3j94JnWdFX/w14eUUEok1vijeOEF2Lrd0Cq5+kD7cyvaeeFA18P6/DYDhMf3eiS7b/PmOYA9TSRI5FoMl+EnAdkB2wOh9Y6CNMDNwOA/EuEeX5WjOxw8i+dpMQTrVEzEA7dJFn3yVy8+Cswtl5EqHjWjJx1IMfG2R5iUQz2YxOzfPRu+jEYttOpJdEUJQqNm8WotSnwIlTZCA0QxGETHWPsiiN4CitQWxImTUzbiq2pZ6399nFbGcAlsvj7BjqLxI=

language: generic
sudo: false

os:
  - linux
  - osx

matrix:
  fast_finish: true

install:
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python="${PYTHON_VERSION}"
  - source activate test-environment
  - python -VV
  - pip --version
  - pip install pylint coverage coveralls codacy-coverage pyyaml

script:
  - python setup.py install
  - coverage run setup.py test
  - coverage xml # Needed for codacy.
  - echo "Lint PyTravisCI" && pylint PyTravisCI
  - echo "Lint tests" && pylint tests/**/*.py

after_success:
  - python-codacy-coverage -r coverage.xml
  - coveralls

notifications:
  on_success: change
  on_failure: always
